apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w6k4qh02c-nodejs-gitops
  description: This is GitOps manifest for w6k4qh02c-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=w6k4qh02c-nodejs
    backstage.io/kubernetes-id: w6k4qh02c-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w6k4qh02c-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w6k4qh02c-nodejs
