apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w6k4qh02c-nodejs
  janus-idp.io/tekton: w6k4qh02c-nodejs
  backstage.io/kubernetes-id: w6k4qh02c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w6k4qh02c-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
